module.exports = {
  'primary-color': '#598FE6',
  'info-color': '#598FE6',
  'processing-color': '#598FE6',
  'success-color': '#b1d57f',
  'error-color': '#f45858', // '#e3635e',
  'highlight-color': '#f45858',
  'warning-color': '#f7c35f',
  'normal-color': '#f8f8f8',
  'text-color': '#333',
  'tabs-card-height': '34px',
  'border-radius-base': '2px',
  'border-color-base': '#dee4f5',
  'border-color-split': '#dee4f5',
  'btn-default-bg': '#f8f8f8',
  'btn-default-color': '#666',
  'btn-padding-base': '0 28px',
  'pagination-item-size-sm': '20px',
  'radio-button-bg': '#fff',
  'input-height-sm': '20px',
  'message-notice-content-padding': '15px 28px'
}
